- name: Create domain admin redteam users
  microsoft.ad.user:
    name: "{{ item }}"
    password: "{{ redteam_user_password }}"
    state: present
    enabled: yes
    password_never_expires: yes
    domain_username: "{{ ansible_user }}"
    domain_password: "{{ ansible_password }}"
    domain_server: "{{ domain }}"
  loop: "{{ redteam_domain_all }}"

- name: Assign domain admin group memberships
  microsoft.ad.group:
    name: "{{ item }}"
    members: 
      add: "{{ redteam_domain_all }}"
    state: present
    domain_username: "{{ ansible_user }}"
    domain_password: "{{ ansible_password }}"
    domain_server: "{{ domain }}"
  loop:
    - Domain Admins
    - Enterprise Admins
  when: redteam_domain_all | length > 0

- name: Add domain admins to builtin access groups
  microsoft.ad.group:
    identity: "CN={{ item }},CN=Builtin,DC=lakeplacid,DC=local"
    members:
      add: "{{ redteam_domain_all }}"
    state: present
    domain_username: "{{ ansible_user }}"
    domain_password: "{{ ansible_password }}"
    domain_server: "{{ domain }}"
  loop:
    - Remote Management Users
    - Remote Desktop Users
  when: redteam_domain_all | length > 0