- name: Compromise Logging
  ansible.builtin.include_tasks: logging.yaml

- name: Compromise Auth
  ansible.builtin.include_tasks: auth.yaml

- name: Compromise Defensive Services
  ansible.builtin.include_tasks: services.yaml

- name: Compromise DNS
  ansible.builtin.include_tasks: dns.yaml

- name: Compromise Defender
  ansible.builtin.include_tasks: defender.yaml

- name: Compromise EOAS
  ansible.builtin.include_tasks: eoas.yaml
  loop: "{{ eoas_targets }}"
  loop_control:
    loop_var: target