---
- name: Deploy Owlet Service systemd
  copy:
    dest: /etc/systemd/system/owlet-{{ owlet_agent_name }}.service
    content: |
      [Unit]
      Description=Owlet Agent for {{ owlet_agent_name }}
      After=network.target

      [Service]
      User=root
      WorkingDirectory={{ owlet_deploy_dir }}
      ExecStart={{ owlet_deploy_dir }}/venv/bin/python3 agent.py
      Restart=always

      [Install]
      WantedBy=multi-user.target
  when: ansible_os_family in ["RedHat", "Debian"]

- name: Deploy Owlet Service OpenRC
  copy:
    dest: "/etc/init.d/owlet-{{ owlet_agent_name }}"
    mode: '0755'
    content: |
      #!/sbin/openrc-run
      name="owlet-{{ owlet_agent_name }}"
      command="{{ owlet_deploy_dir }}/venv/bin/python3"
      command_args="agent.py"
      directory="{{ owlet_deploy_dir }}"
      command_background="yes"
      pidfile="/run/${RC_SVCNAME}.pid"
  when: ansible_os_family == "Alpine"

- name: Deploy Owlet Service rc.d
  copy:
    dest: "/usr/local/etc/rc.d/owlet_{{ owlet_agent_name }}"
    mode: '0555'
    content: |
      #!/bin/sh
      # PROVIDE: owlet_{{ owlet_agent_name }}
      # REQUIRE: LOGIN
      . /etc/rc.subr
      name="owlet_{{ owlet_agent_name }}"
      rcvar="owlet_{{ owlet_agent_name }}_enable"
      command="{{ owlet_deploy_dir }}/venv/bin/python3"
      command_args="agent.py &"
      owlet_{{ owlet_agent_name }}_chdir="{{ owlet_deploy_dir }}"
      load_rc_config $name
      run_rc_command "$1"
  when: ansible_os_family == "FreeBSD"

#- name: Deploy Owlet Service (NSSM)
#  win_shell: |
#    $BaseDir = "{{ owlet_deploy_dir }}"
#    $NssmPath = "$BaseDir\nssm.exe"
#    $ServiceName = "owlet-{{ owlet_agent_name }}"
#    $PythonPath = "$BaseDir\venv\Scripts\python.exe"
#    $ScriptPath = "$BaseDir\agent.py"
#
#    if (!(Get-Service $ServiceName -ErrorAction SilentlyContinue)) {
#        & $NssmPath install $ServiceName $PythonPath $ScriptPath
#        & $NssmPath set $ServiceName AppDirectory "$BaseDir"
#        & $NssmPath set $ServiceName Start SERVICE_DEMAND_START
#    }
#  when: ansible_os_family == "Windows"

- name: Install Owlet Agent as a Windows Service
  community.windows.win_nssm:
    name: "owlet-{{ owlet_agent_name }}"
    executable: "{{ [owlet_deploy_dir, 'nssm.exe'] | path_join }}"
    application: "{{ [owlet_deploy_dir, 'venv', 'Scripts', 'python.exe'] | path_join }}"
    app_parameters: "{{ [owlet_deploy_dir, 'agent.py'] | path_join }}"
    app_directory: "{{ owlet_deploy_dir }}"
    username: "LocalSystem"
    state: present
  when: ansible_os_family == "Windows"