---
# --- LINUX SECTION (Debian & RHEL) ---
- name: Install Python and Pip on Linux
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
      - python3-setuptools # needed in some instances of minimal installs (docker)
    state: present
  when: ansible_os_family != "Windows" and ansible_distribution != "Alpine"

- name: Install Python and Pip on Alpine
  ansible.builtin.package:
    name:
      - py3-pip # alpine
      - py3-setuptools # alpine, needed in some instances of minimal installs (docker)
    state: present
  when: ansible_distribution == "Alpine"

# --- WINDOWS SECTION ---
- name: Check if Python is installed
  ansible.windows.win_command: where.exe python
  register: python_check
  ignore_errors: true
  changed_when: false
  when: ansible_os_family == "Windows"

- name: Download Python Installer for Windows
  ansible.windows.win_get_url:
    url: "https://www.python.org/ftp/python/3.11.5/python-3.11.5-amd64.exe"
    dest: '{{ ansible_env.TEMP }}\python_installer.exe'
  when: 
    - ansible_os_family == "Windows"
    - python_check.rc != 0

- name: Install Python on Windows (Silent)
  ansible.windows.win_package:
    path: '{{ ansible_env.TEMP }}\python_installer.exe'
    arguments: '/quiet InstallAllUsers=1 PrependPath=1' # installs to program files and to system path
    state: present
  when: 
    - ansible_os_family == "Windows"
    - python_check.rc != 0

- name: Remove installer
  ansible.windows.win_file:
    path: '{{ ansible_env.TEMP }}\python_installer.exe'
    state: absent
  when: 
    - ansible_os_family == "Windows"
    - python_check.rc != 0