[windows]
blue1_smb  ansible_host=10.100.2.9  agent_id=blue1_smb
blue2_smb  ansible_host=10.100.3.9  agent_id=blue2_smb
blue1_iis  ansible_host=-10.100.2.10 agent_id=blue1_iis
blue1_iis  ansible_host=-10.100.3.10 agent_id=blue2_iis


[windows:vars]
ansible_user=cia
ansible_password=ColdWar123!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_port=5985
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore