# Ansible inventory file for the target machines
# Currently in testing state, vars will change
[all]
10.100.2.9
10.100.2.10
10.100.2.11
10.100.3.9
10.100.3.10
10.100.3.11

[all:vars]
ansible_user = cia
ansible_password = ColdWar123!
ansible_connection = winrm
ansible_winrm_server_cert_validation = ignore
