# Ansible inventory file for the target machines
# Currently in testing state, vars will change
[all]
10.2.1.2
10.2.1.3
10.2.1.1

[all:vars]
ansible_user = king
ansible_password = Change.me123!
ansible_connection = winrm
ansible_winrm_server_cert_validation = ignore
