---
#####
# Critical vars - change these
#####

webgui_users:             # Users that can log into the website frontend
  admin:                  # username
    password: "admin"     # password
    role: "admin"         # role - admin, analyst, or guest
webhook_url: "https://discord.com/api/webhooks/1485690055547682941/UrOvm3shNIhzZn454NEvywXyDqwSG4DVPnlIHYn_o9CzeURc0Rds7e5ZdkFCt3sq1LUU?thread_id=1485700572207382528"           # Discord webhook url (empty string if none). This can be changed after deploy by modifying config.json and restarting the docker containers.
birdsnest_allow_ips_web:   # IPs that the Nginx proxy will allow to webserver web (frontend) endpoints. Set to your jumpboxes' IPs/range.
  - 127.0.0.1
  - 0.0.0.0/0
birdsnest_allow_ips_agent: # IPs that the Nginx proxy will allow to webserver agent (backend) endpoints. Set to the inscope IPs/ranges.
  - 127.0.0.1
  - 0.0.0.0/0


#####
# Critical vars that should be automated safely - just confirm that they're still good
#####

birdsnest_host_local: "{{ birdsnest_host.split(':')[:-1] | join(':') | regex_replace('^\\[|\\]$', '') }}" # Public URL of server used for linking and certs. note: is NOT used for starting the server listener (that is always 0.0.0.0)
birdsnest_port_local: "{{ birdsnest_host.split(':') | last }}" # External port to listen on

#####
# Variables below this line are not critical and can almost certainly be left on their defaults
#####

# Deploy vars
birdsnest_deploy_dir: "/birdsnest"
birdsnest_gunicorn_workers: 1 # per replica
birdsnest_webserver_replicas: 1
birdsnest_proxy_container: "nginx:1.28.2"
birdsnest_database_image: "postgres:18.3"
birdsnest_python_container: "alpine:3.19"
birdsnest_nginx_max_size: "50M"

# Derived values can still be overridden if needed
public_url: "https://{{ birdsnest_host }}"
logfile: "log.txt"

# server config.json values
secret_key: "{{ lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits,special') }}"
stale_time: 300
default_webhook_sleep_time: 0.25
max_webhook_msg_per_minute: 50
create_test_data: false
database_creds: "birdsnest:birdsnestpwd"
database_location: "database:5432"
database_db: "birdsnestdb"
authconfig_strict_ip: false
authconfig_strict_user: false
authconfig_create_incident: false
authconfig_log_attempt_successful: true
birdsnest_token_metadata:
  added_by: "default"