---
#- name: Ensure Docker is installed and running
#  ansible.builtin.package:
#    name: docker.io  # Use 'docker-ce' if using the official Docker repos
#    state: present

#- name: Ensure Python dependencies for Docker are present
#  ansible.builtin.pip:
#    name: 
#      - requests
#      - pyyaml
#    state: present

#- name: Install Docker Compose plugin
#  ansible.builtin.package:
#    name: docker-compose-v2
#    state: present
#  when: ansible_os_family == "Debian"

#- name: Install Docker Compose plugin
#  ansible.builtin.dnf:
#    name: docker-compose-plugin
#    state: present
#  when: ansible_os_family == "RedHat"

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

- name: Ensure deployment directory exists
  file:
    path: "{{ whackamole_deploy_dir }}"
    state: directory
    mode: '0755'

- name: Ensure log.txt exists (preventing docker directory mapping error)
  file:
    path: "{{ whackamole_deploy_dir }}/log.txt"
    state: touch
    mode: '0755'

- name: Ensure repos/ exists (preventing docker directory mapping error)
  file:
    path: "{{ whackamole_deploy_dir }}/repos/"
    state: directory
    mode: '0755'

- name: Copy files
  copy:
    src: "{{ item }}"
    dest: "{{ whackamole_deploy_dir }}/"
  with_items:
    - models.py
    #- requirements.txt
    - server.py
    - shared.py
    - utilities.py
    - worker.py
    - agents
    - modules
    - static
    - templates

- name: Deploy Nginx config file
  template:
    src: nginx.conf.j2
    dest: "{{ whackamole_deploy_dir }}/nginx.conf"

- name: Deploy Docker Compose config file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ whackamole_deploy_dir }}/docker-compose.yaml"

- name: Deploy webserver config file
  template:
    src: config.json.j2
    dest: "{{ whackamole_deploy_dir }}/config.json"

- name: Ensure OpenSSL is installed
  package:
    name: openssl
    state: present

- name: Generate self-signed SSL Certificate
  command: >
    openssl req -x509 -newkey rsa:4096 -nodes
    -keyout {{ whackamole_deploy_dir }}/key.pem
    -out {{ whackamole_deploy_dir }}/cert.pem
    -days 365
    -subj "/CN={{ whackamole_host_local }}"
  #openssl req -x509 -newkey rsa:4096 -nodes -keyout key.pem -out cert.pem -days 365 -subj "//CN=127.0.0.1" # WINDOWS
  args:
    creates: "{{ whackamole_deploy_dir }}/cert.pem"

- name: Pull and Build Docker Images
  community.docker.docker_compose_v2:
    project_src: "{{ whackamole_deploy_dir }}"
    build: policy
    state: present
  ignore_errors: true # first time may fail

- name: Pull and Build Docker Images Attempt 2
  community.docker.docker_compose_v2:
    project_src: "{{ whackamole_deploy_dir }}"
    build: policy
    state: present