- name: Add local user to the Administrators group
  ansible.windows.win_group_membership:
    name: "Administrators"
    members:
      - "{{ item }}"
    state: present
  loop: "{{ legit_all }}"
  ignore_errors: yes
  #loop: "{{ legit_local_all }}"

- name: Add local user to the Remote Desktop Users group
  ansible.windows.win_group_membership:
    name: "Remote Desktop Users"
    members:
      - "{{ item }}"
    state: present
  loop: "{{ legit_all }}"
  ignore_errors: yes
  #loop: "{{ legit_local_all }}"