[windows]
10.100.2.9
10.100.2.10
10.100.2.11
10.100.3.9
10.100.3.10
10.100.3.11

[windows:vars]
ansible_user=cia
ansible_password=ColdWar123!
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_port=5985
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore
