---
- name: Add questions file
  ansible.builtin.copy:
    src: "files/questions.csv"
    dest: "{{ question_loc }}"
    owner: root
    group: root
  become: yes

- name: Add trivia script
  ansible.builtin.template:
    src: "templates/trivia_night.py.j2"
    dest: "{{ trivia_loc }}"
    owner: root
    group: root
  become: yes

 - name: Check if users exist
    ansible.builtin.user:
    name: "{{ item }}"
  loop: "{{ users }}"
  check_mode: true
  register: existing_users

- name: Add alias to bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ item.item }}/.bashrc"
    line: "alias sudo='python3 {{ trivia_loc }} && '"
    insertafter: EOF
  loop: "{{ existing_users.results }}"
  when: item.state | d('') == 'present'
  become: yes
