---
- name: Add files
  ansible.builtin.copy:
    src: "files"
    dest: "{{ loc }}"
    owner: root
    group: root
  become: yes

 - name: Check if users exist
    ansible.builtin.user:
    name: "{{ item }}"
  loop: "{{ users }}"
  check_mode: true
  register: existing_users

- name: Add alias to bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ item.item }}/.bashrc"
    line: "alias sudo='(source {{ loc }}/trivia/bin/activate && python3 {{ loc }}/trivia_night.py) && '"
    insertafter: EOF
  loop: "{{ existing_users.results }}"
  when: item.state | d('') == 'present'
  become: yes
