---
#####
# Critical vars that should be automated safely - just confirm that they're good 
#####

# Agent Config Vars - You probably need to change these for each deployment.
owlet_agent_name: "auth"      # Agent name. Must be unique per agent per host. For example, if this is a generic auth log monitor, name it 'auth'
owlet_auth_token: "{{ birdsnest_token }}" # Initial token to use for registration, found in agent_auth_tokens from main server deploy or from /web/management page
owlet_server_url: "https://{{ birdsnest_host }}/" # Server IP to connect to - must be in format https://{ip}:{port}/


##########
# Variables below this line are not critical and can almost certainly be left on the default values
##########


# More Agent Config Vars
owlet_debug_print: true       # TRUE to print log messages to stdout in addition to the logfile
owlet_sleeptime: 60
owlet_server_timeout: 5
owlet_auth_log_path: ""
owlet_auth_parser: ""

# Ansible Deployment Vars - You probably shouldn't be changing these
#owlet_task_create: false
#owlet_task_name: "owlet"
#owlet_task_interval: 300 #seconds. cron needs this to be an even minutes value (so divisible by 60)
owlet_agent_executable: "agent.py"
owlet_service_start: true
owlet_deploy_dir: "{{ [ (ansible_os_family == 'Windows') | ternary('C:\\owlet', '/owlet'), owlet_agent_name, '' ] | path_join }}"

# More Agent Config Options - You probably shouldn't be changing these
owlet_agent_type: "owlet"
owlet_logfile: "log.txt"
owlet_statusfile: "status.txt"
owlet_statefile: "state.json"