[ubuntu_vms]
10.100.2.3
10.100.2.4
10.100.2.5
10.100.2.6
10.100.2.7
10.100.2.8
10.100.3.3
10.100.3.4
10.100.3.5
10.100.3.6
10.100.3.7
10.100.3.8
[ubuntu_vms:vars]
ansible_user=cia
ansible_ssh_pass=ColdWar123!
ansible_become_pass=ColdWar123!
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root