---
#####
# Critical vars that should be automated safely - just confirm that they're good 
#####

# Agent Config Vars - You probably need to change these for each deployment.
kingfisher_agent_name: "usermgr"      # Agent name. Must be unique per agent per host. For example, if this is a generic auth log monitor, name it 'auth'
kingfisher_auth_token: "{{ birdsnest_token }}" # Initial token to use for registration, found in agent_auth_tokens from main server deploy or from /web/management page
kingfisher_server_url: "https://{{ birdsnest_host }}/" # Server IP to connect to - must be in format https://{ip}:{port}/
kingfisher_docker: true

##########
# Variables below this line are not critical and can almost certainly be left on the default values
##########


# More Agent Config Vars
kingfisher_disarm: false
kingfisher_debug_print: true       # TRUE to print log messages to stdout in addition to the logfile
kingfisher_sleeptime: 60
kingfisher_server_timeout: 5

# Ansible Deployment Vars - You probably shouldn't be changing these
#kingfisher_task_create: false
#kingfisher_task_name: "kingfisher"
#kingfisher_task_interval: 300 #seconds. cron needs this to be an even minutes value (so divisible by 60)
kingfisher_agent_executable: "agent.py"
kingfisher_service_start: true
kingfisher_deploy_dir: "{{ [ (ansible_os_family == 'Windows') | ternary('C:\\kingfisher', '/kingfisher'), kingfisher_agent_name, '' ] | path_join }}"

# More Agent Config Options - You probably shouldn't be changing these
kingfisher_agent_type: "kingfisher"
kingfisher_logfile: "log.txt"
kingfisher_statusfile: "status.txt"
kingfisher_statefile: "state.json"