---
#- name: Import Wazuh GPG key
#  ansible.builtin.command:
#    cmd: >
#      gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg
#      --import
#  args:
#    stdin: "{{ lookup('url', 'https://packages.wazuh.com/key/GPG-KEY-WAZUH') }}"
#    creates: /usr/share/keyrings/wazuh.gpg

- name: Import Wazuh GPG key
  ansible.builtin.shell: |
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
    gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && \
    chmod 644 /usr/share/keyrings/wazuh.gpg
  args:
    executable: /bin/bash

- name: Set permissions on Wazuh keyring
  ansible.builtin.file:
    path: /usr/share/keyrings/wazuh.gpg
    mode: '0644'

- name: Add Wazuh APT repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main'
    filename: wazuh
    state: present

#- name: Add Wazuh APT repository
#  ansible.builtin.command:
#    cmd: 'echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

#- name: Install Wazuh agent
#  ansible.builtin.command:
#    cmd: 'WAZUH_MANAGER="{{ wazuh_manager_ip }}" apt-get install wazuh-agent'

- name: Install Wazuh agent
  ansible.builtin.apt:
    name: wazuh-agent
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Wazuh agent
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: yes
    state: started