---
- name: Get all local users with a home directory
  ansible.builtin.shell: "getent passwd | awk -F: '$6 ~ /^\/home/ {print $1, $6}'"
  register: local_users
  changed_when: false

- name: Clear shell history for all users
  ansible.builtin.shell: |
    truncate -s 0 {{ item.split()[1] }}/.bash_history
    truncate -s 0 {{ item.split()[1] }}/.zsh_history
  args:
    removes: "{{ item.split()[1] }}/.bash_history"
  loop: "{{ local_users.stdout_lines }}"
  failed_when: false

- name: Truncate system logs
  ansible.builtin.shell: |
    truncate -s 0 /var/log/syslog
    truncate -s 0 /var/log/auth.log
    truncate -s 0 /var/log/kern.log
    truncate -s 0 /var/log/wtmp
    truncate -s 0 /var/log/btmp
    truncate -s 0 /var/log/lastlog
  changed_when: true

- name: Clear journald logs
  ansible.builtin.command: journalctl --vacuum-time=1s
  changed_when: true