---
- name: Copy Docker setup script (Ubuntu)
  ansible.builtin.copy:
    src: docker-setup-ubuntu.sh
    dest: /opt/docker-setup.sh
    owner: root
    group: root
    mode: '0744'
  when: ansible_distribution == "Ubuntu"

- name: Copy Docker setup script (Debian)
  ansible.builtin.copy:
    src: docker-setup-debian.sh
    dest: /opt/docker-setup.sh
    owner: root
    group: root
    mode: '0744'
  when: ansible_distribution == "Debian"

- name: Copy Docker setup script (RHEL/Rocky/Fedora)
  ansible.builtin.copy:
    src: docker-setup-rhel.sh
    dest: /opt/docker-setup.sh
    owner: root
    group: root
    mode: '0744'
  when: ansible_os_family == "RedHat"

- name: Run Docker setup script
  ansible.builtin.shell: /opt/docker-setup.sh
  ignore_errors: true