[usa_linux]
redteam_client ansible_host=10.100.6.89
blue1-cross-check ansible_host=10.100.2.3
blue1-hat-trick ansible_host=10.100.2.4
blue1-triple-deke ansible_host=10.100.2.5
blue1-toe-drag ansible_host=10.100.2.6
blue1-clapper ansible_host=10.100.2.7
blue1-backcheck ansible_host=10.100.2.8

[ussr_linux]
blue2-cross-check ansible_host=10.100.3.3
blue2-hat-trick ansible_host=10.100.3.4
blue2-triple-deke ansible_host=10.100.3.5
blue2-toe-drag ansible_host=10.100.3.6
blue2-clapper ansible_host=10.100.3.7
blue2-backcheck ansible_host=10.100.3.8

[linux:children]
usa_linux
ussr_linux

[linux:vars]
ansible_user=cia
ansible_connection = ssh
ansible_python_interpreter=/usr/bin/python3