all:
  children:
    iis:
      hosts:
        armory:
          ansible_host: "10.2.1.1"
          paperking_agent_name: iis
          paperking_disarm: true
          paperking_ports: [80]
          paperking_services: ['W3SVC']
          paperking_packages: ['Web-Server']
          paperking_protected_folders: ['C:\\Windows\\System32\\inetsrv\\config','C:\\inetpub\\wwwroot','C:\\Windows\\System32\\inetsrv\\w3wp.exe','C:\\Windows\\System32\\inetsrv\\inetmgr.exe']
    smb:
      hosts:
        sewers:
          ansible_host: "10.2.1.2"
          paperking_agent_name: smb
          paperking_disarm: true
          paperking_ports: [445,137,138,139]
          paperking_services: ['LanmanServer']
          paperking_packages: ['FS-FileServer']
          paperking_protected_folders: ['C:\\Shares','C:\\Windows\\System32\\srv2.sys']
    dns:
      hosts:
        fortress:
          ansible_host: "10.2.1.3"
          paperking_agent_name: dns
          paperking_disarm: true
          paperking_ports: [53]
          paperking_services: ['DNS']
          paperking_packages: ['DNS']
          paperking_protected_folders: ['C:\\Windows\\System32\\dns','C:\\Windows\\System32\\dns.exe'] #C:\Windows\NTDS\
    gitlab:
      hosts:
        dungeon:
          ansible_host: "10.2.1.4"
          paperking_agent_name: gitlab
          paperking_disarm: true
          paperking_ports: [80]
          paperking_services: ['gitlab-ctl','apache2']
          paperking_packages: ['gitlab-ee','apache2']
          paperking_protected_folders: ['/etc/gitlab/','/etc/apache2','/var/opt/gitlab/']
    irc:
      hosts:
        cathedral:
          ansible_host: "10.2.1.5"
          paperking_agent_name: irc
          paperking_disarm: true
          paperking_ports: [6667]
          paperking_services: ['inspircd']
          paperking_packages: ['inspircd']
          paperking_protected_folders: ['/etc/inspircd','/usr/sbin/inspircd','/lib/systemd/system/inspircd.service']
    nginx:
      hosts:
        gallows:
          ansible_host: "10.2.1.6"
          paperking_agent_name: nginx
          paperking_disarm: true
          paperking_ports: [80]
          paperking_services: ['nginx']
          paperking_packages: ['nginx']
          paperking_protected_folders: ['/etc/nginx','/var/www/html','/usr/sbin/nginx','/lib/systemd/system/nginx.service']
    docker:
      hosts:
        market:
          ansible_host: "10.2.1.7"
          paperking_agent_name: docker
          paperking_disarm: true
          paperking_ports: []
          paperking_services: ['docker']
          paperking_packages: ['docker.io']
          paperking_protected_folders: ['/etc/docker','/var/lib/docker/','/usr/bin/docker','/usr/bin/dockerd','/lib/systemd/system/docker.service']
    mysql:
      hosts:
        stables:
          ansible_host: "10.2.1.8"
          paperking_agent_name: mysql
          paperking_disarm: true
          paperking_ports: [3306]
          paperking_services: ['mysql']
          paperking_packages: ['mysql-server']
          paperking_protected_folders: ['/etc/mysql','/var/lib/mysql/','/usr/sbin/mysqld','/lib/systemd/system/mysql.service']
    apache2:
      hosts:
        pigeontower:
          ansible_host: "10.2.1.9"
          paperking_agent_name: apache2
          paperking_disarm: true
          paperking_ports: [80]
          paperking_services: ['apache2']
          paperking_packages: ['apache2']
          paperking_protected_folders: ['/etc/apache2','/usr/sbin/apache2','/lib/systemd/system/apache2.service','/var/www/html']

# Groups
    # Hosts for the Teams
    inscope:
      children:
        iis:
        smb:
        dns:
        gitlab:
        irc:
        nginx:
        docker:
        mysql:
        apache2:
    #scoring_all:
    #  #children:
    #  #  scoring_workers:
    #  hosts:
    #    scoring:
    #      ansible_host: "192.169.1.1"
    # Hosts for jumpboxes
    jumpblue:
      hosts:
    #    jumpblue1:
    #      ansible_host: "172.20.0.41"
    #    jumpblue2:
    #      ansible_host: "172.20.0.42"
    #    jumpblue3:
    #      ansible_host: "172.20.0.43"
    #    jumpblue4:
    #      ansible_host: "172.20.0.44"
    #    jumpblue5:
    #      ansible_host: "172.20.0.45"
        jumpblue6:
          ansible_host: "10.20.1.20"
        jumpblue7:
          ansible_host: "10.20.1.21"
    #    jumpblue8:
    #      ansible_host: "172.20.0.48"
    #    jumpblue9:
    #      ansible_host: "172.20.0.49"
    #    jumpblue10:
    #      ansible_host: "172.20.0.40"
        proxy_central:
      #hosts:
      #  jumpred_proxy_central1:
      #    ansible_host: "192.168.10.100"
    proxy:
      hosts:
        jumpred_proxy1:
          ansible_host: "192.168.10.111"
        jumpred_proxy2:
          ansible_host: "192.168.10.112"
        jumpred_proxy3:
          ansible_host: "192.168.10.113"
        jumpred_proxy4:
          ansible_host: "192.168.10.114"
        jumpred_proxy5:
          ansible_host: "192.168.10.115"
        jumpred_proxy6:
          ansible_host: "192.168.10.116"
        jumpred_proxy7:
          ansible_host: "192.168.10.117"
        jumpred_proxy8:
          ansible_host: "192.168.10.118"
        jumpred_proxy9:
          ansible_host: "192.168.10.119"
        jumpred_proxy10:
          ansible_host: "192.168.10.120"
        jumpred_proxy11:
          ansible_host: "192.168.10.121"
        jumpred_proxy12:
          ansible_host: "192.168.10.122"
        jumpred_proxy13:
          ansible_host: "192.168.10.123"
        jumpred_proxy14:
          ansible_host: "192.168.10.124"
    jumpred:
      children:
        proxy:
      hosts:
        jumpred1:
          ansible_host: "192.168.10.11"
        jumpred2:
          ansible_host: "192.168.10.12"
        jumpred3:
          ansible_host: "192.168.10.13"
        jumpred4:
          ansible_host: "192.168.10.14"
        jumpred5:
          ansible_host: "192.168.10.15"
        jumpred6:
          ansible_host: "192.168.10.16"
        jumpred7:
          ansible_host: "192.168.10.17"
        jumpred8:
          ansible_host: "192.168.10.18"
        jumpred9:
          ansible_host: "192.168.10.19"
        jumpred10:
          ansible_host: "192.168.10.20"
    proxy_all:
      children:
        proxy:
        proxy_central:
    jumpboxes:
      children:
        jumpblue:
        jumpgrey:
        jumpred:

# OS-based groups
    # Hosts that are Windows
    windows:
      children:
        iis:
        smb:
        dns:
    # Hosts that are Linux
    debian:
      children:
        gitlab:
        irc:
        nginx:
        #proxy_all:
    ubuntu:
      children:
        docker:
        mysql:
        apache2:
        jumpboxes:
    linux:
      children:
        debian:
        ubuntu:
    unix:
      children:
        linux:
        
    gui:
      children:
        windows:
        ubuntu: