all:
  children:

    mcp:
      hosts:
        blue1-cross-check:
          ansible_host: "10.100.2.3"
        blue2-cross-check:
          ansible_host: "10.100.3.3"
    nginx:
      hosts:
        blue1-hat-trick:
          ansible_host: "10.100.2.4"
        blue2-hat-trick:
          ansible_host: "10.100.3.4"
    mysql:
      hosts:
        blue1-triple-deke:
          ansible_host: "10.100.2.5"
        blue2-triple-deke:
          ansible_host: "10.100.3.5"
    mail:
      hosts:
        blue1-toe-drag:
          ansible_host: "10.100.2.6"
        blue2-toe-drag:
          ansible_host: "10.100.3.6"
    grafana:
      hosts:
        blue1-clapper:
          ansible_host: "10.100.2.7"
        blue2-clapper:
          ansible_host: "10.100.3.7"
    rsyslog:
      hosts:
        blue1-backcheck:
          ansible_host: "10.100.2.8"
        blue2-backcheck:
          ansible_host: "10.100.3.8"
    smb:
      hosts:
        blue1-dump-n-chase:
          ansible_host: "10.100.2.9"
        blue2-dump-n-chase:
          ansible_host: "10.100.3.9"
    iis:
      hosts:
        blue1-snapshot:
          ansible_host: "10.100.2.10"
        blue2-snapshot:
          ansible_host: "10.100.3.10"
    dns:
      hosts:
        blue1-bardown:
          ansible_host: "10.100.2.11"
        blue2-bardown:
          ansible_host: "10.100.3.11"
    ad:
      children:
        dns:
    dc:
      children:
        dns:
  
    proxy_central:
      #hosts:
      #  jumpred_proxy_central1:
      #    ansible_host: "192.168.10.100"
    proxy:
      hosts:
        jumpred_proxy1:
          ansible_host: "192.168.10.111"
        jumpred_proxy2:
          ansible_host: "192.168.10.112"
        jumpred_proxy3:
          ansible_host: "192.168.10.113"
        jumpred_proxy4:
          ansible_host: "192.168.10.114"
        jumpred_proxy5:
          ansible_host: "192.168.10.115"
        jumpred_proxy6:
          ansible_host: "192.168.10.116"
        jumpred_proxy7:
          ansible_host: "192.168.10.117"
        jumpred_proxy8:
          ansible_host: "192.168.10.118"
        jumpred_proxy9:
          ansible_host: "192.168.10.119"
        jumpred_proxy10:
          ansible_host: "192.168.10.120"
        jumpred_proxy11:
          ansible_host: "192.168.10.121"
        jumpred_proxy12:
          ansible_host: "192.168.10.122"
        jumpred_proxy13:
          ansible_host: "192.168.10.123"
        jumpred_proxy14:
          ansible_host: "192.168.10.124"
    jumpred:
      children:
        proxy:
      hosts:
        jumpred1:
          ansible_host: "192.168.10.11"
        jumpred2:
          ansible_host: "192.168.10.12"
        jumpred3:
          ansible_host: "192.168.10.13"
        jumpred4:
          ansible_host: "192.168.10.14"
        jumpred5:
          ansible_host: "192.168.10.15"
        jumpred6:
          ansible_host: "192.168.10.16"
        jumpred7:
          ansible_host: "192.168.10.17"
        jumpred8:
          ansible_host: "192.168.10.18"
        jumpred9:
          ansible_host: "192.168.10.19"
        jumpred10:
          ansible_host: "192.168.10.20"
    proxy_all:
      children:
        proxy:
        proxy_central:
    jumpboxes:
      children:
        jumpblue:
        jumpgrey:
        jumpred:

    inscope:
      children:
        mcp:
        nginx:
        mysql:
        mail:
        grafana:
        rsyslog:
        smb:
        iis:
        dns:

    debian:
      children:
        #proxy:
    ubuntu:
      children:
        jumpboxes:
        mcp:
        nginx:
        mysql:
        mail:
        grafana:
        rsyslog:
    linux:
      children:
        debian:
        ubuntu:
    windows:
      children:
        smb:
        iis:
        dns:
    gui:
      children:
        windows:
        ubuntu: