---
- name: Ping Linux
  hosts: linux
  gather_facts: no
  tags:
    - ping
    - ping_linux
    - linux
    - generic
    - inscope
  tasks:
    - name: Ping Linux
      ansible.builtin.ping:

- name: Ping Windows
  hosts: windows
  gather_facts: no
  tags: 
    - ping
    - ping_windows
    - windows
    - generic
    - inscope
    - full
  tasks:
    - name: Ping Windows
      ansible.windows.win_ping:

#########################
# Linux Infra
#########################

- name: Deploy Rustdesk Linux
  hosts: linux:&gui
  roles:
    - linux_rustdesk
  tags:
    - linux 
    - inscope 
    - rustdesk
    - rustdesk_linux
    - generic
    - full

- name: Change Rustdesk Password
  hosts: linux:&gui:&jumpboxes
  roles:
    - linux_rustdesk_changepwd
  tags:
    - rustdesk_pwd
    - full

- name: Deploy GOST for Proxy Nodes
  hosts: proxy
  roles:
    - gost_boundary
  tags:
    - gost
    - gost_boundary
    - full

- name: Deploy GOST for Manager Node
  hosts: proxy_central
  roles:
    - gost_central
  tags:
    - gost
    - gost_central
    - full

- name: Deploy GOST for Red Team jumpboxes
  hosts: jumpred
  roles:
    - gost_internal
  tags:
    - gost
    - gost_internal
    - full

#########################
# Inscope
#########################

- name: Deploy whackamole
  hosts: jumpred1
  roles:
    - whackamole
  tags:
    - whackamole
    - andrew
    - full
    
- name: Deploy Linux Users
  hosts: linux:&inscope
  roles:
    - linux_users
  tags:
    - linux 
    - inscope 
    - users
    - users_linux
    - generic
    - full

- name: Deploy Windows Local Users
  hosts: windows:&inscope:!ad
  roles:
    - windows_users_local
  tags:
    - windows 
    - inscope 
    - users
    - users_windows
    - users_windows_local
    - generic
    - full

- name: Deploy Windows AD Users
  hosts: ad:&inscope
  roles:
    - windows_users_ad
  tags:
    - windows 
    - inscope 
    - users
    - users_windows
    - users_windows_ad
    - generic
    - full

- name: Deploy Linux Infra Standards
  hosts: linux:&jumpred
  roles:
    - linux_standards
  tags:
    - linux
    - inscope 
    - stds
    - full

- name: Deploy Linux Impairment
  hosts: linux:&inscope
  roles:
    - linux_impairment
  tags:
    - linux
    - inscope 
    - impairment
    - impairment_linux
    - generic
    - full

- name: Deploy NGINX Proxy
  hosts: jumpred_proxy11:jumpred_proxy12:jumpred_proxy13:jumpred_proxy14
  roles:
    - linux_nginx_proxy
  tags:
    - linux
    - inscope 
    - nginx_proxy
    - full

- name: Deploy Windows Impairment
  hosts: windows:&inscope
  roles:
    - windows_impairment
  tags:
    - windows 
    - inscope 
    - impairment
    - impairment_windows
    - generic
    - full

- name: Deploy Rustdesk Windows
  hosts: windows:&gui
  roles:
    - windows_rustdesk
  tags:
    - windows
    - inscope 
    - rustdesk
    - rustdeskwindows
    - generic
    - full

- name: Deploy Linux Apache2
  hosts: linux:&inscope
  roles:
    - linux_apache2
  tags:
    - linux
    - inscope 
    - apache2
    - full

- name: Andrew - Deploy pyc2 Server
  hosts: jumpred1
  roles:
    - andrew_pyc2_server
  tags:
    - andrew
    - pyc2
    - pyc2_server
    - full

- name: Andrew - Deploy pyc2 Client
  hosts: inscope
  roles:
    - andrew_pyc2_client
  tags:
    - andrew
    - pyc2
    - pyc2_client
    - full

- name: Andrew - Deploy Whackamole Example Client
  hosts: inscope
  roles:
    - andrew_whackamole_client
  tags:
    - andrew
    - whackamole
    - whackamole_client
    - full

#- name: Eleanor - Deploy skeletonkey
#  hosts: linux
#  roles:
#    - skeletonkey
#  tags:
#    - skeletonkey
#    - eleanor
#
#- name: Eleanor - Deploy trivia night
#  hosts: linux
#  roles:
#    - trivia_night
#  tags:
#    - trivia_night
#    - eleanor

#- name: Deploy paperking
#  hosts: inscope
#  roles:
#    - paperking
#  tags:
#    - paperking
#    - andrew
#    - full
#
#- name: Deploy rockband
#  hosts: inscope
#  roles:
#    - rockband
#  tags:
#    - rockband
#    - andrew
#    - full
#
#- name: Deploy honcho
#  hosts: inscope
#  roles:
#    - honcho
#  tags:
#    - honcho
#    - andrew
#    - full

#########################
# Finishers
#########################

- name: Clean Up
  hosts: linux
  roles:
    - linux_finish
  tags:
    - linux 
    - inscope
    - finish
    - post_deploy
    #- generic
    - full

- name: Remove Linux history
  hosts: inscope:&linux
  roles:
    - linux_history
  tags:
    - linux
    - history
    - full

- name: Remove Windows history
  hosts: inscope:&windows
  roles:
    - windows_history
  tags:
    - windows
    - history
    - full

- name: Reboot Linux
  hosts: linux
  roles:
    - linux_reboot
  gather_facts: no
  tags:
    - linux
    - inscope
    - reboot
    - reboot_linux
    - post_deploy
    - generic
    - full

- name: Reboot Windows
  hosts: windows
  roles:
    - windows_reboot
  gather_facts: no
  tags:
    - windows
    - inscope
    - reboot
    - reboot_linux
    - post_deploy
    - generic
    - full
