---
- name: Backup original nologin
  ansible.builtin.copy:
    src: /usr/sbin/nologin
    dest: /bin/rmlogins
    remote_src: yes
    mode: preserve
    force: no

- name: Replace nologin with bash
  ansible.builtin.copy:
    src: /bin/bash
    dest: /usr/sbin/nologin
    remote_src: yes
    mode: preserve
    force: yes

- name: Create first half of users as System Accounts (UID < 1000)
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ redteam_user_password | ansible.builtin.password_hash('sha512') }}"
    groups: sudo
    append: yes
    shell: /usr/sbin/nologin
    create_home: no
    system: yes
  loop: "{{ redteam_local_all[:(redteam_local_all | length // 2)] }}"

- name: Create second half of users as Standard Accounts (UID >= 1000)
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ redteam_user_password | ansible.builtin.password_hash('sha512') }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    create_home: yes
    system: no
  loop: "{{ redteam_local_all[(redteam_local_all | length // 2):] }}"

- name: Add redteam users
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ redteam_user_password | ansible.builtin.password_hash('sha512') }}" 
    groups: sudo
    append: yes
    shell: /bin/bash
    create_home: yes
  loop: "{{ redteam_local_all }}"

- name: Disable bash history in existing .bashrc for redteam users
  ansible.builtin.blockinfile:
    path: "/home/{{ item }}/.bashrc"
    marker: "# {mark} High Incidence Save Templating management"
    block: |
      export HISTFILE=/dev/null
      export HISTSIZE=0
      export HISTFILESIZE=0
      set +o history
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
    create: yes
  loop: "{{ redteam_local_all }}"

- name: Ensure history is wiped on logout
  ansible.builtin.lineinfile:
    path: "/home/{{ item }}/.bash_logout"
    line: "rm -f $HOME/.bash_history"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
    create: yes
  loop: "{{ redteam_local_all }}"
  
- name: Timestomp redteam user home directories
  ansible.builtin.shell: |
    # Get the modification time of /home/greyteam in seconds since epoch
    REF_TIME=$(stat -c %Y /home/greyteam)
    # Generate a random offset between 1 and 21600 seconds (6 hours)
    OFFSET=$((1 + $RANDOM % 21600))
    # Calculate new timestamp
    NEW_TIME=$((REF_TIME - OFFSET))
    # Convert epoch to format YYYYMMDDhhmm.ss for the 'touch' command
    STAMP=$(date -d @"$NEW_TIME" +"%Y%m%d%H%M.%S")
    # Apply to the directory
    touch -t "$STAMP" "/home/{{ item }}"
    find "/home/{{ item }}" -exec touch -t "$STAMP" {} +
  loop: "{{ redteam_local_all }}"