---
- name: Add existing users to sudo group
  ansible.builtin.command: "usermod -aG sudo {{ item }}"
  loop: "{{ legit_all }}"
  register: usermod_result
  failed_when: false
  ignore_errors: true
  changed_when: "'does not exist' not in usermod_result.stderr"