---
- name: Ensure all legit local users have sudo
  ansible.builtin.user:
    name: "{{ item }}"
    groups: sudo
    append: yes
  loop: "{{ legit_all }}"
  ignore_errors: yes
  #loop: "{{ legit_local_all }}"