---
- name: Create working dir
  ansible.builtin.file:
    path: "{{ working_dir }}"
    state: directory
    mode: '0777'
    owner: root
    group: root

- name: Install Rustdesk
  ansible.builtin.include_tasks: install_rustdesk.yaml

- name: Delete working dir
  ansible.builtin.file:
    path: "{{ working_dir }}"
    state: absent