---
- name: Deploy Service systemd
  copy:
    dest: /etc/systemd/system/{{ whackamole_service_name }}.service
    content: |
      [Unit]
      Description={{ whackamole_service_description }}
      After=network.target

      [Service]
      User=root
      WorkingDirectory={{ whackamole_agent_deploy_dir }}
      ExecStart={{ whackamole_agent_deploy_dir }}/venv/bin/python3 {{ whackamole_agent_executable }}
      Restart=always

      [Install]
      WantedBy=multi-user.target
  when: ansible_os_family in ["RedHat", "Debian"]

- name: Install Agent as a Windows Service
  community.windows.win_nssm:
    name: "{{ whackamole_service_name }}"
    executable: "{{ [whackamole_agent_deploy_dir, 'nssm.exe'] | path_join }}"
    application: "{{ [whackamole_agent_deploy_dir, 'venv', 'Scripts', 'python.exe'] | path_join }}"
    app_parameters: "{{ [whackamole_agent_deploy_dir, whackamole_agent_executable] | path_join }}"
    app_directory: "{{ whackamole_agent_deploy_dir }}"
    username: "LocalSystem"
    state: present
  when: ansible_os_family == "Windows"