- name: Create resolved.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

#- name: Create DNS override file to resolve domains
#  ansible.builtin.copy:
#    dest: /etc/systemd/resolved.conf.d/dns_override.conf
#    content: |
#      [Resolve]
#      DNS={{ mgmt_dns[0] }}
#      FallbackDNS={{ mgmt_dns[1] }}
#      Domains=~{{ domain }} {{ domain }}
#    mode: '0644'
#  register: dns_dropin

- name: Deploy Local DNS Overrides
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: ".*\\s+{{ item.name | regex_escape }}$"
    line: "{{ item.ip }} {{ item.name }}"
    state: present
    create: yes
  loop: "{{ dns_overrides | default([]) }}"
  when:
    - dns_overrides is defined
    - dns_overrides | length > 0

- name: Append poison entries
  ansible.builtin.blockinfile:
    path: /etc/hosts
    insertafter: EOF
    block: |
      127.0.0.1 {{ dns_localhost_overrides | join(' ') }}
  when:
    - dns_localhost_overrides is defined
    - dns_localhost_overrides | length > 0

- name: Flush DNS cache
  ansible.builtin.command: resolvectl flush-caches

- name: Restart systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted